### ISSUE TITLE
paper-globaal.yml is resetted on static server restart

### ISSUE THREAD

**Issue by danzelgeb** [HttpMarco/polocloud#184]
Everytime my staric instace is restartung the paper-gllobal.yml is getting resetted.

**Comment by RECHERGG** [comment]
I was able to reproduce the issue where the paper-global.yml file gets reset every time the static instance restarts. I have noted this as a bug in [Notion](https://zircon-brie-606.notion.site/paper-global-yml-resets-on-static-service-restart-95259ad88d624af0b85f6c60d12f05a1) for further investigation.

**Comment by RECHERGG** [comment]
> [!TIP]
> We have fixed this bug in our development branch.
> You can view the commit here: https://github.com/HttpMarco/polocloud/commit/3115bc7984901ff000847a543b2184fd9a7500dc

The fix will be included in the the upcoming release. Stay tuned! 😊
